env:
  global:
    - CODECLIMATE_REPO_TOKEN=28c86855122bc245dd440cd9e39ba32a11eab19562afd4aafa0cfcdb3afdc26f
language: node_js
node_js:
  - stable
cache: yarn
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
script:
  - yarn lint && yarn test
  - yarn codecov
notifications:
  email: false
